const BASE = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:4000/api/v1';

export const NEST_API = {
  AUTH: {
    REGISTER: `${BASE}/auth/register`,
    LOGIN_EMAIL: `${BASE}/auth/login/email`,
    LOGIN_PHONE_SEND: `${BASE}/auth/login/phone/send`,
    LOGIN_PHONE_VERIFY: `${BASE}/auth/login/phone/verify`,
    ONBOARDING_COMPLETE: `${BASE}/auth/onboarding/complete`,
    VERIFY_CURRENT_PHONE_SEND: `${BASE}/auth/verify-phone/send`,
    VERIFY_CURRENT_PHONE_CONFIRM: `${BASE}/auth/verify-phone/confirm`,
    GOOGLE_COMPLETE_PROFILE: `${BASE}/auth/google/complete-profile`,
    REFRESH: `${BASE}/auth/refresh`,
    LOGOUT: `${BASE}/auth/logout`,
    SWITCH_ROLE: `${BASE}/auth/switch-role`,
    BECOME_HOST: `${BASE}/auth/become-host`,
    ME: `${BASE}/auth/me`,
    ME_SUPABASE: `${BASE}/auth/me/supabase`,
  },
  LISTINGS: {
    CREATE: `${BASE}/listings`,
    LIST_MINE: `${BASE}/listings/me`,
    SEARCH: `${BASE}/listings/search`,
    FEED:   `${BASE}/listings/feed`,
    FIND_ONE: (id: string) => `${BASE}/listings/${id}`,
    UPDATE: (id: string) => `${BASE}/listings/${id}`,
    SUBMIT: (id: string) => `${BASE}/listings/${id}/submit`,
    PAUSE:    (id: string) => `${BASE}/listings/${id}/pause`,
    RESUME:   (id: string) => `${BASE}/listings/${id}/republier`,
    ARCHIVE: (id: string) => `${BASE}/listings/${id}`,
    SET_TARIFS_PERSONNES: (id: string) => `${BASE}/listings/${id}/tarifs-personnes`,
    SET_TARIFS_NUITS: (id: string) => `${BASE}/listings/${id}/tarifs-nuits`,
    PHOTO_UPLOAD_PARAMS: (id: string) => `${BASE}/listings/${id}/photos/upload-params`,
    ADD_PHOTO: (id: string) => `${BASE}/listings/${id}/photos`,
    REMOVE_PHOTO: (id: string, photoId: string) => `${BASE}/listings/${id}/photos/${photoId}`,
    SET_MAIN_PHOTO: (id: string, photoId: string) => `${BASE}/listings/${id}/photos/${photoId}/principal`,
    LIST_EQUIPEMENTS: `${BASE}/listings/equipements`,
    SET_EQUIPEMENTS: (id: string) => `${BASE}/listings/${id}/equipements`,
    PRICE_PREVIEW: (id: string) => `${BASE}/listings/${id}/price-preview`,
  },
  WALLET: {
    ME:                   `${BASE}/wallet/me`,
    WITHDRAW:             `${BASE}/wallet/withdraw`,
    ADMIN_WITHDRAWALS:    `${BASE}/admin/wallet/withdrawals`,
    ADMIN_VALIDATE:       (id: string) => `${BASE}/admin/wallet/withdrawals/${id}/validate`,
    ADMIN_REJECT:         (id: string) => `${BASE}/admin/wallet/withdrawals/${id}/reject`,
  },
  RESERVATIONS: {
    CREATE:                 `${BASE}/reservations`,
    MINE:                   (statut?: string) => statut ? `${BASE}/reservations/me?statut=${statut}` : `${BASE}/reservations/me`,
    FIND_ONE:               (id: string) => `${BASE}/reservations/${id}`,
    CONFIRM:                (id: string) => `${BASE}/reservations/${id}/confirm`,
    CANCEL:                 (id: string) => `${BASE}/reservations/${id}/cancel`,
    UPLOAD_CHECKIN_PHOTOS:  (id: string) => `${BASE}/reservations/${id}/checkin/upload`,
    UPLOAD_CHECKOUT_PHOTOS: (id: string) => `${BASE}/reservations/${id}/checkout/upload`,
    COMPLETE_CHECKOUT:      (id: string) => `${BASE}/reservations/[id]/checkout/complete`.replace('[id]', id),
    ADD_ETAT_LIEUX:              (id: string) => `${BASE}/reservations/${id}/etat-lieux`,
    ETAT_LIEUX_UPLOAD_PARAMS:   (id: string) => `${BASE}/reservations/${id}/etat-lieux/upload-params`,
    CHECKIN_PROPRIO:        (id: string) => `${BASE}/reservations/${id}/checkin-proprio`,
    CHECKOUT_PROPRIO:       (id: string) => `${BASE}/reservations/${id}/checkout-proprio`,
    CONFIRM_CHECKIN:        (id: string) => `${BASE}/reservations/${id}/checkin/confirm`,
    REFUSE_CHECKIN:         (id: string) => `${BASE}/reservations/${id}/checkin/refuse`,
    REPORT_ABSENT:          (id: string) => `${BASE}/reservations/${id}/absent`,
    RATE_TENANT:            (id: string) => `${BASE}/reservations/${id}/rate-tenant`,
    RATE_OWNER:             (id: string) => `${BASE}/reservations/${id}/rate-owner`,
    SIGNAL_NOSHOW:          (id: string) => `${BASE}/reservations/${id}/signal-noshow`,
  },
  USERS: {
    ME: `${BASE}/users/me`,
  },
  KYC: {
    SUBMIT: `${BASE}/kyc/submit`,
    SUBMIT_SELFIE: `${BASE}/kyc/submit-selfie`,
  },
  UPLOAD: {
    KYC_DOCUMENT:   `${BASE}/upload/kyc-document`,
    KYC_SELFIE:     `${BASE}/upload/kyc-selfie`,
    ETAT_LIEUX:     `${BASE}/upload/etat-lieux`,
    CHECKIN_PHOTO:  `${BASE}/upload/checkin-photo`,
  },
  CALENDRIER: {
    GET:    (logementId: string) => `${BASE}/calendrier/${logementId}`,
    CREATE: (logementId: string) => `${BASE}/calendrier/${logementId}`,
    DELETE: (logementId: string, indispoId: string) => `${BASE}/calendrier/${logementId}/${indispoId}`,
  },
  DISPUTES: {
    CREATE: `${BASE}/disputes`,
  },
  DASHBOARD: {
    OWNER_STATS:      `${BASE}/dashboard/owner/stats`,
    PENDING_ACTIONS:  `${BASE}/dashboard/owner/pending-actions`,
    RECENT_ACTIVITY:  `${BASE}/dashboard/owner/recent-activity`,
    UPCOMING_EVENTS:  `${BASE}/dashboard/owner/upcoming-events`,
  },
} as const;
